"""Generated by the spec-flow run engine (simulated impl).
Node: anonymiser — Event anonymiser (daily salt). Spec: specs/anonymiser.md. Replace the body with the real implementation."""


def anonymiser():
    raise NotImplementedError("see specs/anonymiser.md")
