"""Generated by the spec-flow run engine (simulated impl).
Node: consent_banner — Consent banner widget. Spec: specs/consent_banner.md. Replace the body with the real implementation."""


def consent_banner():
    raise NotImplementedError("see specs/consent_banner.md")
