"""Generated by the spec-flow run engine (simulated impl).
Node: ep_query — GET /query. Spec: specs/ep_query.md. Replace the body with the real implementation."""


def ep_query():
    raise NotImplementedError("see specs/ep_query.md")
