"""Generated by the spec-flow run engine (simulated impl).
Node: ingest — Event ingestion. Spec: specs/ingest.md. Replace the body with the real implementation."""


def ingest():
    raise NotImplementedError("see specs/ingest.md")
