"""Generated by the spec-flow run engine (simulated impl).
Node: schema — Rollup schema + migrations. Spec: specs/schema.md. Replace the body with the real implementation."""


def schema():
    raise NotImplementedError("see specs/schema.md")
